### PR TITLE
This solves issue #1

### PR DESCRIPTION
**Pull request by dneise**
The previous version had a problem, with fits.fz files, with a ZTILELEN not equal to 1 .. .see #1.

This version now completely uses the C++ implementation of the fits reader implemented by Etienne Lyard in [MARS/mcore](https://trac.fact-project.org/browser/trunk/Mars/mcore)

This header only implementation was fairly easy to wrap using Cython, i.e. I only wrappend what was needed to read a file. Not all public methods are made available or so ... 

Due to this, I do not need to import my own fork of fitsio, since the reader is completely implemented in C++ and I only use this to read the contents of the `fits.fz` file. However... it turned out to be much easier for me, to still use the normal [fitsio from pypi](https://pypi.python.org/pypi/fitsio/) for making the header available. 
The header e.g. contains some timestamps including the NIGHT, RUN number, in case one does not want to parse these from the filename or path. 

So to sum it up, this implementation performing better (as it returns all events ... not only a part) ... and it has 
less dependencies. 

It is quite fast (single core) ~60..80 events/s  uncalibrated (possibly io blocked) ... ~30 events/s calibrated (possibly CPU blocked) 

---- 

Ah I should say: 

I was not able/willing to use the Mars header files without any modification. 
I removed all `#ifdef __EXCEPTION` like [this one here](https://trac.fact-project.org/browser/trunk/Mars/mcore/fits.h#L142) 

Since I simply hate the way precompiler foo destroys readibility.... 

Also I needed access to some stuff hidden inside the C++ `fits` class, so I made some stuff public instead of protected and implemented some methods to give me descriptions of the fits table columns.... technical details, but the bottom line is. In case Etienne or somebody else further develops the code in Mars (or debugs something), then it is not straight forward to push these changes in here...

----

There is one unit test to make sure the calibrated output looks correct. Thanks to @MaxNoe  for this.
So I am pretty sure that this implementation, while being completely different, is still doing the right thing.

### CODE REVIEW

**Comment by dneise** [comment]
Ah yes, the unit test compares the calibrated data from this project with calibrated data from fact-tools.

It does so only for the first event and only for the first pixel. 

I tried it for a pixels, but it failed .. for pixel 18. 
Here you see why ...
zfits_facttools_comparison_unittest_for_pixel_18

apparently there is a spike not removed in the comparison data I have .. while this implementation tries to remove the spike (at least a bit) ... 

I am not sure what to take from this ... maybe the `fact_tools_reference` was produced without spike removal.

**Comment by dneise** [comment]
Also this project does not contain any (array-)-DRS-time-correction whatsoever. But it never did so far... so this should not be a reason not to merge this PR.

**Comment by dneise** [comment]
I would especially like to know if this builds on a MAC... so if anybody with a mac ... maybe @mackaiver  could check it out and try to build it ... I'd be grateful.

If it does build on a Mac, I was wondering if this should at some point find its way into pyfact.

**Comment by dneise** [comment]
Here is an [example ipynb](https://github.com/fact-project/zfits/blob/586353c8f5d22216eab59f95ab74ea27d34abebe/tests/resources/zfits_interface.ipynb)

**Comment by maxnoe** [comment]
The fact-tools reference only applied DRS Calibration, no spike removal or time calib.

**Comment by kbruegge** [comment]
So doing `pip install -e .` produces
```
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c zfits/factfits.cpp -o build/temp.macosx-10.11-x86_64-3.6/zfits/factfits.o -std=c++11
    zfits/factfits.cpp:464:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
```

Am I doing something wrong?

**Comment by maxnoe** [comment]
Sounds like clang is missing an include flag for the numpy headers

**Comment by dneise** [comment]
I also fail to build it on ISDC, which is where I developed it for... so...
I guess it's simply another C/C++ project that happens to build on exactly one machine.

     pip install -e .

Is exactly the way I also built it on my laptop

**Comment by dneise** [comment]
Okay .. so now it builds 
 * on ISDC (GCC 4.4.7 20120313) and 
 * on my laptop  (GCC 5.4.0 20160609)

In the last commit I added

    include_dirs=[numpy.get_include(), 

so maaayybee this might help with the issue @mackaiver had on the MAC. Maybe you can try now again?

I do usually something like this:

    cd ~/fact/zfits
    git pull
    python setup.py clean --all
    pip install -e .
    pytest

**Review by maxnoe — APPROVED** [review]

**Comment by maxnoe** [comment]
I guess this is the only chance we have ;(

**Comment by dneise** [comment]
:+1:  thanks

**Pull request merged**
